# Copyright Matleena Piesala 2018

# https://svalbard.reaktor.com/mainchamber
#
# initializing system
# ... init var = G H N R T
# ... init const = A I U E O
# ... init rules
# ... G => GN
# ... R => NT
# ... N => RH
# ... H => TG
# ... T => HH
# complete
# input seed: ************
# seed accepted
# starting up...
# eval seed on generation 0
# FATAL ERROR
# debug head on generation 6
# printing output...
#HHGNHHGNGNRHNTTGHHGNHHGNGNRHNTTGGNRHNTTGRHHHHHGNNTTGTGTGTGTGGNRHUNTTGTGTGTGTGGNRHTGTGGNRHTGTGGNRHTGTGGNRHTGTGGNRHGNRHNTTGRHHHHHGNTGTGGNRHTGTGGNRHGNRHNTTGRHHHHHGNTGTGGNRHTGTGGNRHGNRHNTTGRHHHHHGNORHHHHHGNHHGNHHGNHHGNHHGNGNRHNTTGHHGNHHGNGNRHNTTGHHGNHHGNGNRHNTTGGNRHNTTGRHHHHHGNNTTGTGTGTGTGGNRHRHHHHHGNHHGNHHGNHHGNHHGNGNRHNTTGATGTGGNRHTGTGGNRHGNRHNTTGRHHHHHGNTGTGGNRHTGTGGNRHGNRHNTTGRHHHHHGNHHGNHHGNGNRHNTTGHHGNHHGNGNRHNTTGGNRHNTTGRHHHHHGNNTTGTGTGTGTGGNRHERHHHHHGNHHGNHHGNHHGNHHGNGNRHNTTGHHGNHHGNGNRHNTTGHHGNHHGNGNRHNTTG

# My solution for decrypting the seed.

Code1="HHGNHHGNGNRHNTTGHHGNHHGNGNRHNTTGGNRHNTTGRHHHHHGNNTTGTGTGTGTGGNRHUNTTGTGTGTGTGGNRHTGTGGNRHTGTGGNRHTGTGGNRHTGTGGNRHGNRHNTTGRHHHHHGNTGTGGNRHTGTGGNRHGNRHNTTGRHHHHHGNTGTGGNRHTGTGGNRHGNRHNTTGRHHHHHGNORHHHHHGNHHGNHHGNHHGNHHGNGNRHNTTGHHGNHHGNGNRHNTTGHHGNHHGNGNRHNTTGGNRHNTTGRHHHHHGNNTTGTGTGTGTGGNRHRHHHHHGNHHGNHHGNHHGNHHGNGNRHNTTGATGTGGNRHTGTGGNRHGNRHNTTGRHHHHHGNTGTGGNRHTGTGGNRHGNRHNTTGRHHHHHGNHHGNHHGNGNRHNTTGHHGNHHGNGNRHNTTGGNRHNTTGRHHHHHGNNTTGTGTGTGTGGNRHERHHHHHGNHHGNHHGNHHGNHHGNGNRHNTTGHHGNHHGNGNRHNTTGHHGNHHGNGNRHNTTG"

# adds number 7 (could be any character that is not in Code1) to every vowel
# because the encryption is 1 char -> 2 char
# and vowels are constants

for v in 'AIUEO':
    Code1 = Code1.replace(v,v+'7')

# decrypting for six rounds
count = 1
while count < 7:
    CodeS = " ".join(Code1[i:i+2] for i in range(0, len(Code1), 2)) #adds space after every two chars
    Code2 = CodeS.replace('GN','G')
    Code3 = Code2.replace('NT','R')
    Code4 = Code3.replace('RH','N')
    Code5 = Code4.replace('TG','H')
    Code6 = Code5.replace('HH','T')
    Code1 = Code6.replace(" ","") #remove all spaces CodeC = Cleaned
    count += 1

CodeF = Code1.replace(" ","") #remove spaces
CodeF = CodeF.replace("7","") #remove added char '7's from the string
print(CodeF) #CodeF = final string = password for mainvault
